apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
       preferredDuringSchedulingIgnoredDuringExecution:
       - weight: 1
         preference:
           matchExpressions:
           - key: hardware
             operator: In
             values:
             - gpu
  containers:
  - name: nginx
    image: nginx:latest
  # nodeSelector:
  #   hardware: gpu

  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"