apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    purpose: podAffinity
spec:
  containers:
  - name: nginx
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - podAffinity
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - podAffinity
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx:latest